import type { ImproveRecommendationsOutput } from "@/ai/flows/improve-recommendations";

export const mockRecommendations: ImproveRecommendationsOutput = [
  {
    title: "The Good Place",
    year: "2016",
    genre: "Comedy",
    platform: "Netflix",
    synopsis: "A woman finds herself in a heaven-like afterlife and tries to become a better person.",
    mainActors: ["Kristen Bell", "Ted Danson"],
    directLink: "#",
    confidenceScore: 95,
    reviews: "Widely acclaimed for its originality, humor, and philosophical depth.",
    director: "Michael Schur",
    writer: "Michael Schur",
    ratings: "IMDb: 8.2, Rotten Tomatoes: 97%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
  },
  {
    title: "Black Mirror",
    year: "2011",
    genre: "Sci-Fi",
    platform: "Netflix",
    synopsis: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    mainActors: ["Bryce Dallas Howard", "Daniel Kaluuya"],
    directLink: "#",
    confidenceScore: 88,
    reviews: "Praised for its cautionary tales about technology, though some seasons are considered stronger than others.",
    director: "Various",
    writer: "Charlie Brooker",
    ratings: "IMDb: 8.8, Rotten Tomatoes: 83%",
    contentType: "Serie",
    language: "English",
    originCountry: "UK"
  },
  {
    title: "The Mandalorian",
    year: "2019",
    genre: "Action",
    platform: "Disney+",
    synopsis: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    mainActors: ["Pedro Pascal", "Gina Carano"],
    directLink: "#",
    confidenceScore: 92,
    reviews: "Loved for its classic Star Wars feel, compelling characters, and groundbreaking visual effects.",
    director: "Various",
    writer: "Jon Favreau",
    ratings: "IMDb: 8.7, Rotten Tomatoes: 93%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
  },
  {
    title: "Fleabag",
    year: "2016",
    genre: "Comedy",
    platform: "Amazon Prime",
    synopsis: "A dry-witted woman, known only as Fleabag, has no filter as she navigates life and love in London.",
    mainActors: ["Phoebe Waller-Bridge", "Sian Clifford"],
    directLink: "#",
    confidenceScore: 90,
    reviews: "A masterpiece of modern television, celebrated for its sharp writing, fourth-wall breaks, and emotional honesty.",
    director: "Harry Bradbeer",
    writer: "Phoebe Waller-Bridge",
    ratings: "IMDb: 8.7, Rotten Tomatoes: 100%",
    contentType: "Serie",
    language: "English",
    originCountry: "UK"
  },
  {
    title: "Severance",
    year: "2022",
    genre: "Thriller",
    platform: "Apple TV+",
    synopsis: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
    mainActors: ["Adam Scott", "Britt Lower"],
    directLink: "#",
    confidenceScore: 85,
    reviews: "A chilling and stylish workplace thriller that captivates with its mystery and superb performances.",
    director: "Ben Stiller, Aoife McArdle",
    writer: "Dan Erickson",
    ratings: "IMDb: 8.7, Rotten Tomatoes: 97%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
    },
    {
    title: "Arcane",
    year: "2021",
    genre: "Animation",
    platform: "Netflix",
    synopsis: "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    mainActors: ["Hailee Steinfeld", "Ella Purnell"],
    directLink: "#",
    confidenceScore: 89,
    reviews: "A stunning animated series with a rich story and complex characters, considered one of the best video game adaptations ever.",
    director: "Pascal Charrue, Arnaud Delord",
    writer: "Christian Linke, Alex Yee",
    ratings: "IMDb: 9.0, Rotten Tomatoes: 100%",
    contentType: "Serie",
    language: "English",
    originCountry: "France/USA"
    }
];

export const recentlyViewed: ImproveRecommendationsOutput = [
  {
    title: "Stranger Things",
    year: "2016",
    genre: "Sci-Fi",
    platform: "Netflix",
    synopsis: "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
    mainActors: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    directLink: "#",
    confidenceScore: 91,
    reviews: "A nostalgic and thrilling tribute to '80s sci-fi and horror films.",
    director: "The Duffer Brothers",
    writer: "The Duffer Brothers",
    ratings: "IMDb: 8.7, Rotten Tomatoes: 92%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
  },
  {
    title: "The Crown",
    year: "2016",
    genre: "Drama",
    platform: "Netflix",
    synopsis: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    mainActors: ["Claire Foy", "Olivia Colman", "Imelda Staunton"],
    directLink: "#",
    confidenceScore: 87,
    reviews: "A lavish and impeccably acted historical drama that offers a glimpse into the life of British royalty.",
    director: "Various",
    writer: "Peter Morgan",
    ratings: "IMDb: 8.6, Rotten Tomatoes: 89%",
    contentType: "Serie",
    language: "English",
    originCountry: "UK"
  },
    {
    title: "Ted Lasso",
    year: "2020",
    genre: "Comedy",
    platform: "Apple TV+",
    synopsis: "An American college football coach is unexpectedly recruited to manage an English soccer team.",
    mainActors: ["Jason Sudeikis", "Hannah Waddingham", "Brett Goldstein"],
    directLink: "#",
    confidenceScore: 94,
    reviews: "An uplifting and hilarious series with a surprising amount of heart.",
    director: "Various",
    writer: "Jason Sudeikis, Bill Lawrence",
    ratings: "IMDb: 8.8, Rotten Tomatoes: 92%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA/UK"
  },
   {
    title: "Breaking Bad",
    year: "2008",
    genre: "Crime",
    platform: "Netflix",
    synopsis: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    mainActors: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    directLink: "#",
    confidenceScore: 98,
    reviews: "Often cited as one of the greatest television series of all time, with masterful storytelling and performances.",
    director: "Vince Gilligan, various",
    writer: "Vince Gilligan",
    ratings: "IMDb: 9.5, Rotten Tomatoes: 96%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
  },
  {
    title: "The Office",
    year: "2005",
    genre: "Comedy",
    platform: "Netflix",
    synopsis: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    mainActors: ["Steve Carell", "Rainn Wilson", "John Krasinski"],
    directLink: "#",
    confidenceScore: 96,
    reviews: "A beloved sitcom that perfectly captures the absurdity of office life.",
    director: "Various",
    writer: "Greg Daniels, Ricky Gervais, Stephen Merchant",
    ratings: "IMDb: 9.0, Rotten Tomatoes: 81%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
    },
    {
    title: "Game of Thrones",
    year: "2011",
    genre: "Fantasy",
    platform: "HBO Max",
    synopsis: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    mainActors: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"],
    directLink: "#",
    confidenceScore: 93,
    reviews: "An epic fantasy saga with a massive scope, although the final season was divisive.",
    director: "Various",
    writer: "David Benioff, D. B. Weiss",
    ratings: "IMDb: 9.2, Rotten Tomatoes: 89%",
    contentType: "Serie",
    language: "English",
    originCountry: "USA"
    }
];
